### ISSUE TITLE
Show error when multiple parts with the same ref.des. in schematic

### ISSUE THREAD

**Issue by kiavash-google** [google/pcbdl#1]
Like this code must show error:

	# USB Connection section
	DM << (
		R("100k", "R58", to=VBUS, populated=False),
		R("200k", "R57", to=gnd, populated=False),
	)

	DP << (
		R("100k", "R58", to=VBUS, populated=False),
		R("200k", "R57", to=gnd, populated=False),
	)

**Comment by amstan** [comment]
Yep, this needs a failing test.

Context.new_part should check that "part.name not in (part.name for part in self.parts_list)"
