### ISSUE TITLE
How to export .netlist file and svg or HTML. please provide one example.

### ISSUE THREAD

**Issue by dev-techshlok** [google/pcbdl#26]
Hello 
I tried examples but unable to generate a netlist.

Also is ti posible to genrate netlist for Kicad or eagle.

**Comment by amstan** [comment]
> please provide one example

I recommend just going to the pcbdl folder and running `make examples/servo_micro.html` (with the netlistsvg caveat below).

Type `make` for more examples/instructions, especially if you have your own schematics file:
```
amstan@amstan-glaptop:~/Projects/pcbdl (master)% make                                                  
This makefile could be used for automating pcbdl exporting:
        make yourcircuit.html
        make yourcircuit.svg
        make yourcircuit.allegro_third_party/
        make yourcircuit.shell

yourcircuit could be stored anywhere, could be an absolute path.
If the circuit is outside the pcbdl folder (suggested), make needs a -f flag to point it back to this file:
        make -f /path/to/pcbdl/Makefile /another/path/to/yourcircuit.html
```


> I tried examples but unable to generate a netlist.

Depends on why you're unable.

If you got the following error:

```['/usr/bin/env', 'node', '/home/amstan/netlistsvg/bin/netlistsvg.js', '--skin', '/home/amstan/netlistsvg/lib/analog.svg', '/tmp/netlistsvg_input_j9vf7adr.json', '-o', '/tmp/netlistsvg_output_wflvvx_4.svg']
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/amstan/netlistsvg/bin/netlistsvg.js'
```

I expect you need to [install netlistsvg](https://google.github.io/pcbdl/doc/_build/html/netlistsvg.html#installation) (your bug prompted me to publish those instructions).

> Also is ti posible to genrate netlist for Kicad or eagle.

I don't have that implemented yet.
There's a bug open for [Kicad netlist output module](https://github.com/google/pcbdl/issues/5).

Patches welcome!
